### ISSUE TITLE
How to flash it after unlocking the phone?

### ISSUE THREAD

**Issue by AmazingPerson1334** [Xiaomi-fire-unofficial-development/twrp_device_xiaomi_fire#2]
Uh... hello. So I'm working on a project of mine which I will try to port postmarketOS to Redmi 12... and I need some help about flashing the TWRP image for Xiaomi Redmi 12 in your previous repository.

Now I flashed TWRP before but it was on a completely different device ( A Samsung J7 Prime specifically) and I tried to flash an Android 14 gsi on the Redmi 12 but I got the phone pretty much bricked and got a replacement phone. I don't want to do the same mistake again.

I would pretty much appreciate clear instructions on how to flash properly after unlocking the phone.

**Comment by AntarcticShaurant** [comment]
Hello!
May i ask what steps did you follow to flash the GSI?

Also, please avoid using the recovery from my old repository, since it doesn't support decryption, and is full of bugs, since it's too old.

Me and @shub876 almost done testing the recovery; in fact we're currently fixing MTP and fastbootd, then we'll only have to fix a little bug on backups and we'll be able to release it.

**Comment by AmazingPerson1334** [comment]
Thanks for the heads up, I'll wait for the release then. Again, when you release it I would appreciate some instructions because I'm really new to the Xiaomi devices.

**Comment by AmazingPerson1334** [comment]
Also I can't remember the exact steps with the GSI flashing.

That's all I got for now.

Have a nice day / night!

**Comment by AntarcticShaurant** [comment]
> Also I can't remember the exact steps with the GSI flashing.
> 
> That's all I got for now.
> 
> Have a nice day / night!

No problem, have a nice day/night as well!

**Comment by AntarcticShaurant** [comment]
Hello, i know it's been a while, but we've encountered an unexpected bug, while flashing recovery zips (even thought i should've fixed it by now, i need to test the new build).

The recovery is pretty much stable right now, so if you want I'll tell you how to flash the recovery and the GSI below, and once I'll have tested the recovery, I'll push it to SourceForge and link it here (might even post the img in the releases, I'll think about it later).

### Recovery flashing:
- (Reboot to fastboot) **Hold volume down + power button / adb reboot bootloader**
- (Flash VBMeta) **fastboot  flash vbmeta _[vbmeta-disabled.img.zip](https://github.com/Xiaomi-fire-unofficial-development/twrp_device_xiaomi_fire/files/14420420/vbmeta-disabled.img.zip)_**
- (Flash Recovery to boot) **fastboot flash boot _twrp-boot.img_**
- (Reboot to recovery) **fastboot reboot recovery**
- (Either copy stock boot and recovery to and OTG usb or use MTP to copy them to internal storage)
- (Flash stock boot) **Install > Install Image > Find _stock-boot.img_ > Choose boot partition > Swipe**
- (Inject TWRP to Ramdisk) **Advanced > Install Recovery Ramdisk > Find _twrp-boot.img_ > Swipe**
- Profit!

### GSI flashing:

- (Reboot to Fastbootd) (WARNING: you might brick your phone if you do fastboot reboot fastboot on this phone if you didn't flash twrp first :shrug:, i recommend the first option)
**adb reboot fastboot / fastboot reboot fastboot** 
- (Flash VBMeta) **fastboot flash vbmeta _[vbmeta-disabled.img.zip](https://github.com/Xiaomi-fire-unofficial-development/twrp_device_xiaomi_fire/files/14420425/vbmeta-disabled.img.zip)_**
- (Flash System, remember to unpack the GSI, you need the img) **fastboot flash system gsi.img**
- (Reboot to recovery) **fastboot reboot recovery**
- (Format data) **Wipe > Format Data > type yes**
- (Reboot to system) 
- Again, profit!


Edit1: Feel free to close the issue if you don't need anything else. Otherwise, just ask!

Edit2: Oh by the way, could you tell me what did you mean by brick your device? did you end up in a bootloop? you couldn't reboot to fastboot? etcetera, since if it's something like this, it's pretty much fixable, no need for a replacement phone.

**Comment by AmazingPerson1334** [comment]
yes I did end up in a bootloop, couldn't get into fastboot too so I thought I completely botched it. I was very stupid and actually I discovered that I could have used mtkclient and fastboot again to resolve the issue

**Comment by AmazingPerson1334** [comment]
So yeah I didn't know much about the device then

**Comment by AmazingPerson1334** [comment]
It happened again, and that's how I discovered my device wasn't completely bricked.

Also fastboot boot doesn't work on my device, did you tried fastboot booting with your device?

And I made a postmarketOS (linux port) for Redmi 12 in the meantime (the kernel was a painful experience to successfully compile, I had to consult a maintainer for samsung-gta7litewifi, which also had a mediatek soc and the same kernel version, to fix it)

**Comment by AmazingPerson1334** [comment]
I only got the display and the usb otg, external and internal storage working. But couldn't find a way to make touchscreen work (and the battery too, it says that it's 1% in XFCE4 and then shuts down). FTS_TS complains it couldn't find a bin file in dmesg. Do you know how to get the touchscreen working?

**Comment by AntarcticShaurant** [comment]
> actually I discovered that I could have used mtkclient and fastboot again to resolve the issue

Exactly, that's what i meant. It happens, so no problem.


> It happened again
> 
> Also fastboot boot doesn't work on my device, did you tried fastboot booting with your device?
> 
> And I made a postmarketOS (linux port) for Redmi 12 in the meantime!

Yep, the MT6769H doesn't support fastboot booting, that's why i wrote
 

> **fastboot flash boot _recovery.img_**

and it's a recurring problem, since there are a lot MTK devices that don't support it.
Also congrats for postmarket!


> I only got the display and the usb otg, external and internal storage working. But couldn't find a way to make touchscreen work (and the battery too, it says that it's 1% in XFCE4 and then shuts down). FTS_TS complains it couldn't find a bin file in dmesg. Do you know how to get the touchscreen working?

About the touchscreen part, did you include the related blobs? you might want to check in recovery/root/vendor/firmware/ in this DT.
Also, in my opinion we're going a bit off topic right now, should we move this conversation on your repo's Discussions? or maybe something like Telegram or Email?

**Comment by AmazingPerson1334** [comment]
I'll prefer the email option and I grabbed those blobs and put those blobs in postmarketos rootfs (to /vendor/firmware/) but it didn't work sadly.

**Comment by AntarcticShaurant** [comment]
Alright, contact me on Shaurant@proton.me, i'll check your repo in the meanwhile.
